// @flow
export const generalIcons = {
    ARROW_LEFT: 'ARROW_LEFT',
    BELL: 'BELL',
    CLOSE: 'CLOSE',
    CLOSE_CIRCLE: 'CLOSE_CIRCLE',
    EXTERNAL_LINK: 'EXTERNAL_LINK',
    HEART: 'HEART',
    LOGO: 'LOGO',
    LOGO_FACEBOOK: 'LOGO_FACEBOOK',
    LOGO_GOOGLE: 'LOGO_GOOGLE',
    MENU: 'MENU',
    MULTI_CHOICE_ON: 'MULTI_CHOICE_ON',
    MULTI_CHOICE_OFF: 'MULTI_CHOICE_OFF',
    PIN: 'PIN',
    PROFILE: 'PROFILE',
    SWAP: 'SWAP',
    TICK: 'TICK',
};
