export const SET_SEARCH_CRITERIA = 'search/SET_SEARCH_CRITERIA';
export const RESET_SEARCH_CRITERIA = 'search/RESET_SEARCH_CRITERIA';
export const SEARCH_FLIGHTS: 'search/SEARCH_FLIGHTS' = 'search/SEARCH_FLIGHTS';
