export const airlines = {
    '1T': 'Bulgarian',
    '3J': 'Zip',
    Q5: '40-Mile Air',
    '4R': 'Hamburg',
    '4O': 'Interjet',
    '7A': 'Express Air Cargo',
    P6: 'Privilege Style',
    WP: 'Air Antwerp',
    JY: 'Air Turks and Caicos',
    JU: 'Air Serbia',
    QH: 'Kyrgyzstan',
    XK: 'Corse Méditerranée',
    EI: 'Aer Lingus',
    A8: 'Benin Golf Air',
    RV: 'Caspian',
    '1B': 'Abacus',
    W9: 'Wizz Air UK',
    '6U': 'Air Ukraine',
    E4: 'Aero Asia',
    ZI: 'Aigle Azur',
    AE: 'Mandarin',
    OZ: 'Ozark Air Lines',
    '4K*': 'Askari Aviation',
    '8U': 'Afriqiyah',
    Q9: 'Afrinat',
    KI: 'Adam Air',
    QB: 'Georgian',
    LD: 'Air Hong Kong',
    UX: 'Air Europa',
    IG: 'Meridiana',
    NX: 'Air Macau',
    ZV: 'Air Midwest',
    HM: 'Air Seychelles',
    AF: 'Air France',
    SB: 'Air Caledonie',
    EH: 'SAETA',
    ZW: 'Air Wisconsin',
    GN: 'Air Gabon',
    NQ: 'Air Japan',
    VD: 'SwedJet',
    TT: 'Tigerair Australia',
    '4N': 'Air North Charter',
    QM: 'Air Malawi',
    ML: 'Midway',
    P8: 'Pantanal',
    BM: 'BMI Regional',
    ZX: 'Air Georgian',
    G8: 'Gujarat',
    '7T': 'Tobruk Air',
    '6V': 'Mars RK',
    NH: 'All Nippon',
    TZ: 'Tsaradia',
    '2Q': 'Air Cargo Carriers',
    V7: 'Volotea',
    AB: 'Air Berlin',
    '4D': 'Air Sinai',
    QN: 'Air Armenia',
    AI: 'Air India Limited',
    PJ: 'Air Saint Pierre',
    SZ: 'Air Southwest',
    '8C': 'Shanxi',
    NF: 'Air Vanuatu',
    ZB: 'Monarch',
    CC: 'Macair',
    RB: 'Syrian Arab',
    TN: 'Air Tahiti Nui',
    SW: 'Air Namibia',
    AW: 'Dirgantara',
    PE: "People's",
    JM: 'Jetstar',
    '6G': 'Air Wales',
    IX: 'Air India Express',
    BT: 'Air Baltic',
    EL: 'Ellinair',
    YW: 'Air Nostrum',
    PX: 'Air Niugini',
    G9: 'Air Arabia',
    AC: 'Air Canada',
    AP: 'AlbaStar',
    XT: 'SkyStar',
    UM: 'Air Zimbabwe',
    S2: 'Air Sahara',
    TC: 'Air Tanzania',
    '2J': 'Air Burkina',
    KM: 'Air Malta',
    YT: 'Yeti',
    G4: 'Allegiant Air',
    M3: 'North Flying',
    O4: 'Antrak Air',
    GB: 'ABX Air',
    '8V': 'Wright Air Service',
    '4G*': 'Advance Leasing Company',
    '8T': 'Air Tindi',
    'Z7*': 'ADC',
    JP: 'Adria',
    'EM*': 'Aero Benin',
    A3: 'Aegean',
    '2K': 'Aerogal',
    KD: 'KD Avia',
    KO: 'Alaska Central Express',
    VX: 'Virgin America',
    KH: 'Aloha Air Cargo',
    AA: 'American',
    AX: 'Trans States',
    AN: 'Ansett Australia',
    '5W': 'Astraeus',
    VV: 'Aerosvit',
    WK: 'Edelweiss Air',
    QQ: 'Reno Air',
    FG: 'Ariana Afghan',
    'RV*': 'Africaone',
    Y2: 'Flyglobespan',
    SU: 'Aeroflot Russian',
    '5Z': 'Gonini Air Services',
    '5D': 'DonbassAero',
    '1A': 'Amadeus IT Group',
    JJ: 'LATAM Brasil',
    PL: 'Airstars',
    '8A': 'Atlas Blue',
    GD: 'Air Alpha Greenland',
    HT: 'Aeromist-Kharkiv',
    J2: 'Azerbaijan',
    U3: 'Avies',
    '4Y': 'Yute Air Alaska',
    RS: 'Royal Air Force of Oman',
    '5A': 'Alpine Air Express',
    'ED*': 'Airblue',
    W4: 'Aero Services Executive',
    IZ: 'Arkia Israel',
    M6: 'Amerijet International',
    '4A': 'Air Kiribati',
    EV: 'ExpressJet',
    HP: 'Phoenix',
    VH: 'Viva Air Colombia',
    AM: 'Aeroméxico',
    TL: 'Trans Mediterranean',
    OY: 'Omni Air International',
    IW: 'Wings Air',
    J6: 'AVCOM',
    '2D': 'Aero VIP',
    VB: 'VIVA Aerobus',
    OE: 'Laudamotion',
    GV: 'Grant Aviation',
    JW: 'Vanilla Air',
    '2B': 'Albawings',
    '4C': 'Aires',
    AR: 'Aerolíneas Argentinas',
    AS: 'Alaska , Inc.',
    OB: 'Oasis',
    HC: 'Iceland Express',
    FO: ' of Tasmania',
    OS: 'Austrian',
    IQ: 'Augsburg',
    RU: 'SkyKing Turks and Caicos',
    MO: 'Calm Air',
    GR: 'Gemini Air Cargo',
    NO: 'Neos',
    AU: 'Austral Líneas Aéreas',
    AO: 'Australian',
    AV: 'Avianca',
    A0: 'Avianca Argentina',
    O6: 'Avianca Brazil',
    K8: 'Airlink Zambia',
    B9: 'Air Bangladesh',
    HJ: 'Hellas Jet',
    AK: 'Air Bridge Carriers',
    D7: 'FlyAsianXpress',
    DJ: 'Polynesian Blue',
    I5: 'AirAsia India',
    EX: 'Air Santo Domingo',
    '3G': 'Atlant-Soyuz',
    AZ: 'Alitalia',
    ZE: 'Azteca',
    A2: 'Cielos',
    R7: 'Aserca',
    RX: 'Regent',
    MQ: 'Envoy Air',
    ZS: 'Sama',
    FF: 'Airshop',
    VU: 'Air Ivoire',
    BP: 'Air Botswana',
    GS: 'Tianjin',
    VT: 'Air Tahiti',
    '3N': 'Air Urga',
    VL: 'Air VIA',
    FK: 'Keewatin Air',
    G2: 'Avirex',
    V8: 'Iliamna Air Taxi',
    K6: 'Khalifa',
    VE: 'C.A.I. Second',
    V5: 'Royal Aruban',
    CA: 'Air China',
    Q6: 'Aero Condor Peru',
    '5F': 'Fly One',
    QC: 'Air Corridor',
    NV: 'Air Central',
    CV: 'Cargolux',
    CW: 'Air Marshall Islands',
    ZA: 'Interavia',
    AH: 'Air Algérie',
    ER: 'Astar Air Cargo',
    HO: 'Juneyao',
    EN: 'Air Dolomiti',
    NM: 'Mount Cook',
    EE: 'Aero',
    '4F': 'Air City',
    E8: 'Alpi Eagles',
    KY: 'Air São Tomé and Príncipe',
    PC: 'Pegasus',
    FJ: 'Fiji',
    RC: 'Atlantic',
    NY: 'Air Iceland',
    '2P': 'Air Philippines',
    '2U': 'Air Guinee Express',
    '0A': 'Amber Air',
    DA: 'Air Georgia',
    GL: 'Air Greenland',
    LL: 'Miami Air International',
    '5Y': 'Atlas Air',
    GG: 'Sky Lease Cargo',
    H9: 'Izair',
    HD: 'AIRDO',
    IP: 'Atyrau Air Ways',
    QK: 'Air Canada Jazz',
    KK: 'Atlasjet',
    JS: 'Air Koryo',
    KC: 'Air Astana',
    LV: 'Level',
    '3S': 'Air Guyane Express',
    D4: 'Alidaunia',
    '9I': 'Thai Sky',
    XL: 'Aerolane',
    A6: 'Hongtu',
    TD: 'Tulip Air',
    L8: 'Air Luxor GB',
    LK: 'Air Luxor',
    MK: 'Air Mauritius',
    MD: 'Air Madagascar',
    '9U': 'Air Moldova',
    L9: 'Teamline Air',
    A7: 'Air Plus Comet',
    QO: 'Origin Pacific',
    MR: 'Hunnu Air',
    '3S*': 'Aeroland',
    '2V*': 'Amtrak',
    '8D*': 'Astair',
    F4: 'Albarka Air',
    AJ: 'Aero Contractors',
    '8Y': 'China Postal',
    OT: 'Aeropelican Air Services',
    AD: 'Azul',
    QD: 'Air Class Líneas Aéreas',
    QS: 'Smartwings',
    AG: 'Aruba',
    MC: 'Air Mobility Command',
    RE: 'Stobart Air',
    UU: 'Air Austral',
    ZP: 'Silk Way',
    '6K': 'Asian Spirit',
    A5: 'Hop!',
    R3: 'Yakutia',
    MV: 'Air Mediterranean',
    '2O': 'Air Salone',
    U8: 'Armavia',
    BQ: 'Baltia Air Lines',
    P5: 'AeroRepública',
    BF: 'Aero-Service',
    '5L': 'AeroSur',
    JR: 'Aero California',
    Z3: 'Avient Aviation',
    GM: 'Air Slovakia',
    VW: 'Aeromar',
    CG: ' PNG',
    TY: 'Iberworld',
    FL: 'AirTran',
    TS: 'Air Transat',
    EC: 'easyJet Europe',
    DW: 'Aero-Charter Ukraine',
    U7: 'USA Jet',
    '6R': 'Alrosa Air Company',
    '6A': 'Aviacsa',
    JZ: 'Skyways Express',
    'WD*': 'Amsterdam',
    SM: 'Swedline Express',
    KJ: 'British Mediterranean',
    BX: 'Coast Air',
    YE: 'Aryan Cargo Express',
    VJ: 'Vietjet Air',
    '3O': 'Air Arabia Maroc',
    X9: 'Avion Express',
    UJ: 'Al Masria Universal',
    BO: 'Bouraq Indonesia',
    JD: 'Beijing Capital',
    ID: 'Interlink',
    '8Q*': 'Baker Aviation',
    BA: 'British',
    BG: 'Biman Bangladesh',
    B4: 'Bankair',
    WX: 'CityJet',
    BZ: 'Keystone',
    JA: 'JetSMART',
    J4: 'Jordan International',
    '8H': 'BH Air',
    U4: 'PMTair',
    '4T': 'Belair',
    UP: 'Bahamasair',
    E6: 'Bringer Air',
    LZ: 'Balkan Bulgarian',
    TH: 'Transmile Air Services',
    BS: 'US-Bangla',
    PG: 'Bangkok',
    KF: 'Blue1',
    JV: 'Bearskin Lake',
    B3: 'Bellview',
    BD: 'BMI',
    WW: 'WOW air',
    CH: 'Bemidji',
    BV: 'Blue Panorama',
    '7R': 'BRA',
    '8E': 'Bering Air',
    B2: 'Belavia Belarusian',
    BN: 'Horizon',
    GQ: 'Big Sky',
    V9: 'Star1',
    Y6: 'Batavia Air',
    BU: 'Buryat Aircompany',
    J8: 'Berjaya Air',
    QW: 'Blue Wings',
    SN: 'Brussels',
    '8W?': 'BAX Global',
    DB: 'Brit Air',
    E9: 'Boston-Maine',
    NT: 'Binter Canarias',
    '0B': 'Blue Air',
    FB: 'Bulgaria Air',
    '8N': 'Barents AirLink',
    CJ: 'CityFlyer Express',
    YB: 'Borajet',
    BW: 'Caribbean',
    '7N': 'PAWA Dominicana',
    '5C': 'CAL Cargo',
    '3C': 'RegionsAir',
    R9: 'Camai Air',
    UY: 'Cameroon',
    C6: 'CanJet',
    CP: 'Compass',
    '5T': 'Canadian North',
    W2: 'Canadian Western',
    '9K': 'Cape Air',
    PT: 'West Air Sweden',
    '2G': 'Cargoitalia',
    W8: 'Cargojet',
    C8: 'Chicago Jet Group',
    '8B': 'Caribbean Star',
    V3: 'Carpatair',
    KA: 'Cathay Dragon',
    CX: 'Cathay Pacific',
    KX: 'Cayman',
    '5J': 'Cebu Pacific',
    '9M': 'Central Mountain Air',
    J7: 'ValuJet',
    WE: 'Thai Smile',
    OP: "Chalk's",
    MG: 'Champion Air',
    '2Z': 'Chang An',
    S8: 'Skywise',
    'RP*': 'Chautauqua',
    CI: 'China',
    CK: 'China Cargo',
    MU: 'China Eastern',
    G5: 'China Express',
    WH: 'WebJet Linhas Aéreas',
    CZ: 'China Southern',
    KN: 'China United',
    XO: 'LTE International',
    '3Q': 'KC International',
    X7: 'Chitaavia',
    QI: 'Cimber Sterling',
    C7: 'Rico Linhas Aéreas',
    C9: 'Cirrus',
    CF: 'City',
    G3: 'Gol Transportes Aéreos',
    CT: 'Civil Air Transport',
    '6P': 'Club Air',
    DQ: 'Coastal Air',
    '9L': 'Colgan Air',
    YD: 'Cologne',
    OH: 'PSA',
    MN: 'Comair',
    C5: 'CommutAir',
    KR: 'Comores',
    GJ: 'Eurofly',
    DE: 'Condor Flugdienst',
    CO: 'Continental Express',
    CS: 'Continental Micronesia',
    V0: 'Conviasa',
    CM: 'Copa',
    CQ: 'Sunshine Express',
    XC: 'Corendon',
    CD: 'Corendon Dutch',
    SS: 'Corsairfly',
    F5: 'Cosmic Air',
    '7C': 'Jeju Air',
    OU: 'Croatia',
    QE: 'Crossair Europe',
    CU: 'Cubana de Aviación',
    CY: 'Cyprus',
    YK: 'Cyprus Turkish',
    OK: 'Czech',
    '8L': 'Redhill Aviation',
    XG: 'Sunexpress Deutschland',
    PN: 'Pan American',
    WD: 'WDL Aviation',
    DX: 'DAT Danish Air Transport',
    D0: 'DHL Air Limited',
    ES: 'DHL International',
    L3: 'LTU Austria',
    D3: 'Daallo',
    N2: 'Kabo Air',
    H8: 'Dalavia',
    DD: 'Nok Air',
    '0D': 'Darwin Airline',
    D5: 'Dauair',
    DL: 'Delta Air Lines',
    '2A': 'Deutsche Bahn',
    '1I': 'Sky Trek',
    DH: 'Norwegian Air Norway',
    Z6: 'Dniproavia',
    YU: 'Dominair',
    DO: 'Dominicana de Aviación',
    E3: 'Sabaidee',
    D9: 'Donavia',
    KB: 'Druk Air',
    DI: 'Norwegian Air UK',
    '9E': 'Pinnacle',
    '9A': 'Eagle Express',
    E1: 'Everbread',
    BR: 'EVA Air',
    EY: 'Etihad',
    H7: 'Eagle Air',
    NZ: 'Eagle',
    QU: 'Uganda',
    S9: 'East African Safari',
    EA: 'European Air Express',
    T3: 'Eastern',
    QF: 'Sunstate',
    DK: 'Eastland Air',
    MS: 'Egyptair',
    LY: 'El Al Israel',
    UZ: 'El-Buraq Air Transport',
    EK: 'Emirates',
    EM: 'Empire',
    E0: 'Eos',
    B8: 'Eritrean',
    E7: 'European Aviation',
    OV: 'SalamAir',
    ET: 'Ethiopian',
    RZ: 'Euro Exec Express',
    MM: 'SAM Colombia',
    UI: 'SW Italia',
    K2: 'Eurolot',
    '3W': 'Euromanx',
    '5O': 'Europe Airpost',
    QY: 'European Air Transport',
    EW: 'Eurowings',
    E2: 'Rio Grande Air',
    EZ: 'Sun Air of Scandinavia',
    ZD: 'Ewa Air',
    JN: 'Excel',
    MB: 'MNG',
    OW: 'Executive',
    EO: 'Hewa Bora',
    U2: 'easyJet',
    DS: 'easyJet Switzerland',
    IH: 'Irtysh Air',
    FE: 'Primaris',
    FD: 'Thai AirAsia',
    F6: 'FaroeJet',
    F3: 'Faso',
    FX: 'FedEx Express',
    N8: 'National Air Cargo',
    '4S': 'Finalair Congo',
    AY: 'Finnair',
    FC: 'Finncomm',
    FY: 'Northwest Regional',
    '7F': 'First Air',
    DP: 'First Choice',
    '8F': 'Fischer Air',
    '8D': 'Servant Air',
    B5: 'Flightline',
    PA: 'Pan American World',
    RF: 'Florida West',
    '8W': 'Private Wings',
    F2: 'Fly Air',
    OJ: 'Overland',
    SH: 'Sharp',
    TE: 'Skytaxi',
    LF: 'FlyNordic',
    F7: 'Flybaboo',
    BE: 'Flybe',
    W3: 'Switfair Cargo',
    VY: 'Vueling',
    HK: 'Four Star',
    FH: 'Futura International',
    SJ: 'Freedom Air',
    F9: 'Frontier',
    '2F': 'Frontier',
    FZ: 'Flydubai',
    '9Y': 'Fly Georgia',
    VK: 'Virgin Nigeria',
    GX: 'Pacificair',
    Y5: 'Pace',
    GT: 'GB',
    Z5: 'GMG',
    '7O': 'Galaxy Air',
    '1G': 'Galileo International',
    GC: 'Gambia International',
    G7: 'GoJet',
    GA: 'Garuda Indonesia',
    '4G': 'Gazpromavia',
    A9: 'Georgian',
    ST: 'Germania',
    '4U': 'Germanwings',
    GP: 'Palau Trans Pacific',
    GH: 'Ghana',
    G0: 'Ghana International',
    GK: 'Jetstar Japan',
    DC: 'Golden Air',
    G1: 'Gorkha',
    ZK: 'Great Lakes',
    IJ: 'Spring Japan',
    G6: 'Air Volga',
    J9: 'Jazeera',
    GF: 'Gulf Air',
    GY: 'Tri-MG Intra Asia',
    H6: 'Hageland',
    HR: 'Hahn Air',
    H1: 'Hahn Air Systems',
    HU: 'Hainan',
    '1R': 'Hainan Phoenix',
    '2T': 'Haiti Ambassador',
    HF: 'Hapagfly',
    HB: 'Harbor',
    HQ: 'Thomas Cook',
    HA: 'Hawaiian',
    BH: 'Hawkair',
    HN: 'Heavylift Cargo',
    JB: 'Helijet',
    ZU: 'Helios',
    HW: 'North-Wright',
    '2L': 'Helvetic',
    UD: "Hex'Air",
    '5K': 'Hi Fly',
    H5: 'Mavial Magadan',
    HX: 'Hong Kong',
    RH: 'Republic Express',
    UO: 'Hong Kong Express',
    HH: 'Hope Air',
    QX: 'Horizon Air',
    H4: 'Inter Island',
    IK: 'Lankair',
    II: 'IBC',
    '0C': 'IBL Aviation',
    '1F': 'INFINI',
    '1U': 'Polyot Sirena',
    IB: 'Iberia',
    I2: 'Iberia Express',
    FW: 'Ibex',
    D8: 'Norwegian Air',
    FI: 'Icelandair',
    '6E': 'IndiGo',
    IC: 'Indian',
    I9: 'Indigo',
    IO: 'Indonesian',
    C4: 'Zimex Aviation',
    D6: 'Interair South Africa',
    '3L': 'Intersky',
    I4: 'Interstate',
    IR: 'Iran Air',
    EP: 'Iran Aseman',
    IA: 'Iraqi',
    '2S': 'Satgur',
    MT: 'Thomas Cook',
    '3K': 'Jetstar Asia',
    LS: 'Jet2.com',
    B6: 'JetBlue',
    JF: 'L.A.B. Flying Service',
    '0J': 'Jetclub',
    SG: 'Spicejet',
    JQ: 'Jetstar',
    JX: 'Jett8 Cargo',
    WA: 'KLM Cityhopper',
    KL: 'KLM',
    KE: 'Korean Air',
    LA: 'LATAM Chile',
    '4M': 'LATAM Argentina',
    UC: 'LATAM Cargo Chile',
    PZ: 'TAM Mercosur',
    LU: 'LATAM Express',
    LP: 'LATAM Peru',
    NI: 'Portugalia',
    L5: 'Lufttransport',
    LO: 'LOT',
    LT: 'LongJiang',
    N6: 'Nuevo Continente',
    QV: 'Lao',
    L7: 'Línea Aérea SAPSA',
    NG: 'Lauda Air',
    MP: 'Martinair',
    Q4: 'Starlink Aviation',
    '8M': 'Myanmar International',
    MY: 'Midwest (Egypt)',
    MW: 'Mokulele',
    '7M': 'Mayair',
    M8: 'Mekong',
    IM: 'Menajet',
    MZ: 'Merpati Nusantara',
    YV: 'Mesa',
    XJ: 'Thai AirAsia X',
    MX: 'Mexicana de Aviación',
    ME: 'Middle East',
    YX: 'Midwest',
    M4: 'Mistral Air',
    '2M': 'Moldavian',
    '8I': 'Myway',
    YM: 'Montenegro',
    '5M': 'Sibaviatrans',
    '3R': 'Moskovia',
    M9: 'Motor Sich',
    N4: 'Nordwind',
    VZ: 'Thai Vietjet Air',
    UB: 'Myanma',
    '6N': 'Nordic Regional',
    DV: 'Scat Air',
    P9: 'Peruvian',
    UE: 'Transeuropean',
    N7: 'National',
    NA: 'North American',
    '9O': 'National Cameroon',
    NC: 'Northern Air Cargo',
    CE: 'Nationwide',
    '1N': 'Navitaire',
    RA: 'Nepal',
    EJ: 'New England',
    '2N': 'Yuzhmashavia',
    HG: 'Niki',
    KZ: 'Nippon Cargo',
    XW: 'NokScoot',
    '5N': 'Nordavia',
    NW: 'Northwest',
    J3: 'Northwestern Air',
    DY: 'Norwegian Air Shuttle',
    DN: 'Norwegian Air Argentina',
    DU: 'Norwegian Long Haul',
    LE: 'Norwegian Air Sweden',
    BJ: 'Nouvel Air Tunisie',
    O9: 'Nova Airline',
    VQ: 'Novo Air',
    NK: 'Spirit',
    UQ: "O'Connor ",
    O8: 'Oasis Hong Kong',
    VC: 'Voyageur',
    OA: 'Olympic',
    WY: 'Oman Air',
    '8Q': 'Princess Air',
    R2: 'Orenburg',
    OX: 'Orient Thai',
    OL: 'Samoa Air',
    ON: 'Our Airline',
    O7: 'Ozjet',
    PV: 'St Barth Commuter',
    '9Q': 'PB Air',
    PU: 'PLUNA',
    BL: 'Pacific',
    QR: 'Qatar',
    R6: 'RACSA',
    '1D': 'Radixx',
    V4: 'Vieques Air Link',
    FN: 'Regional Air Lines',
    ZL: 'Regional Express',
    P7: 'Russian Sky',
    RW: 'Republic',
    RL: 'Royal Phnom Penh',
    SL: 'Thai Lion Mentari',
    GZ: 'Air Rarotonga',
    RR: 'Royal Air Force',
    AT: 'Royal Air Maroc',
    R0: 'Royal',
    BI: 'Royal Brunei',
    RJ: 'Royal Jordanian',
    RK: 'Royal Khmer',
    WR: 'WestJet Encore',
    WB: 'Rwandair Express',
    '7S': 'Ryan Air Service',
    RD: 'Ryan International',
    FR: 'Ryanair',
    SA: 'South African',
    W7: 'Western Pacific',
    UL: 'SriLankan',
    SY: 'Sun Country',
    I6: 'Sky Eyes',
    '7G': 'Star Flyer',
    FA: 'Safair',
    HZ: 'Sat',
    SP: 'SATA Air Acores',
    '8S': 'Scorpio Aviation',
    ZY: 'Sky',
    SQ: 'Singapore Cargo',
    SI: 'Skynet',
    XS: 'SITA',
    FT: 'Siem Reap',
    SX: 'Skybus',
    S6: 'Star Air',
    D2: 'Severstal Air Company',
    '5G': 'Skyservice',
    SD: 'Sudan',
    SV: 'Saudia',
    WN: 'Southwest',
    A4: 'Southern Winds',
    WG: 'Sunwing',
    LX: 'Swiss',
    SR: 'Sundair',
    'LZ[46]': 'Swiss Global',
    WV: 'Swe Fly',
    WO: 'World',
    XQ: 'SunExpress',
    AL: 'TransAVIAexport',
    '7L': "Sun D'Or",
    E5: 'Samara',
    SC: 'Shandong',
    '9C': 'Spring',
    '3U': 'Sichuan',
    FM: 'Shanghai',
    ZH: 'Shenzhen',
    NE: 'SkyEurope',
    SO: 'Sunshine',
    JK: 'Spanair',
    '2G*': 'San Juan',
    '1Z': 'Sabre Pacific',
    '1S': 'Sabre',
    '1H': 'Siren-Travel',
    '1Q': 'Sirena',
    '1K': 'Sutra',
    '2C': 'SNCF',
    S0: 'Slok Air Gambia',
    VA: 'Viasa',
    S3: 'Santa Barbara',
    H2: 'Sky Airline',
    OO: 'SkyWest',
    BC: 'Skymark',
    MI: 'SilkAir',
    '6Q': 'Slovak',
    PY: 'Surinam',
    NB: 'Sterling',
    IE: 'Solomon',
    TG: 'Thai',
    TK: 'Turkish',
    T7: 'Twin Jet',
    '3P': 'Tiara Air',
    TI: 'Tol-Air Services',
    BY: 'Thomson',
    PM: 'Tropic Air',
    QT: 'TAMPA',
    K3: 'Taquan Air Services',
    GE: 'TransAsia',
    HV: 'Transavia Holland',
    VR: 'TACV',
    T9: 'Thai Star',
    '9T': 'Transwest Air',
    UN: 'Transaero',
    T5: 'Turkmenhovayollary',
    '7O[50]': 'Travel Service',
    T6: 'Tavrey',
    TW: "T'way Air",
    '6B': 'TUIfly Nordic',
    DT: 'TAAG Angola',
    SF: 'Tassili',
    TJ: 'Tradewind Aviation',
    RO: 'Tarom',
    '3T': 'Turan Air',
    T4: 'TRIP Linhas Aéreas',
    L6: 'Tbilaviamsheni',
    XN: 'XpressAir',
    VO: 'Tyrolean',
    OR: 'TUI Netherlands',
    U5: 'USA3000',
    B7: 'UNI Air',
    UA: 'United',
    '4H': 'United',
    U6: 'Ural',
    UR: 'Uganda',
    UF: 'UM',
    Y4: 'Volaris',
    VI: 'Volga-Dnepr',
    TV: 'Virgin Express',
    VS: 'Virgin Atlantic',
    ZG: 'Viva Macau',
    XF: 'Vladivostok Air',
    LC: 'Varig Logística',
    VM: 'Viaggio Air',
    '9V': 'Vipair',
    RG: 'VRG Linhas Aéreas',
    VP: 'VASP',
    VG: 'VLM',
    UK: 'Vistara',
    WT: 'Wasaya',
    '2W': 'Welcome Air',
    WZ: 'West African',
    YH: 'West Caribbean',
    '8O': 'West Coast Air',
    WS: 'WestJet',
    XP: 'Xtra',
    WF: 'Widerøe',
    IV: 'Wind Jet',
    '7W': 'Windrose Air',
    '8Z': 'Wizz Air Bulgaria',
    W6: 'Wizz Air',
    '1P': 'Worldspan',
    '3W*': 'Wan Air',
    MF: 'Xiamen',
    SE: 'XL France',
    YL: 'Yamal',
    Q3: 'Zambian',
    Z4: 'Zoom',
};
